### ISSUE TITLE
[v0.90.3] java.lang.NoClassDefFoundError issue with FormatCache on Android 6 and lower

### ISSUE THREAD

**Issue by papjul** [pdvrieze/xmlutil#255]
As reported by an user in breezy-weather/breezy-weather#1432, `xmlutil` crashes with the `java.lang.NoClassDefFoundError` exception on Android 6 and lower. It used to work in v0.90.2.

Let me know if you can't reproduce the issue with a minimum code; I will see if I can help.

**Comment by pdvrieze** [comment]
@papjul Do you use any minification? 

The lambda in the case is a function that creates a cache as needed for threadlocals.

As a workaround it should be possible to disable the cache with:
```kotlin
XML {
  policy = DefaultXmlSerializationPolicy(FormatCache.Dummy)
}
```
Note that this path should avoid ever reading the default as creates the policy without setting a temporary policy.

**Comment by pdvrieze** [comment]
Alternatively you may need to inform proguard to keep that class around.

**Comment by papjul** [comment]
I do use minification on release versions. The report from the user is from the debug version as we can see from the logs, so there is no minification. Also, it's specific to Android versions 6 and lower, so it would affect all versions if it was for this reason, right?

**Comment by pdvrieze** [comment]
@papjul I suspect this is an issue with code lowering/R8. I've just pushed a workaround that will just use a dummy cache if an error is thrown creating the default cache.

**Comment by pdvrieze** [comment]
Just released a new version (0.91.1) that has the released workaround.
